---
# tasks file for package-management
- name: Install required packages
  ansible.builtin.package:
    name: "{{ install_packages }}"
    state: present
  ignore_errors: yes

- name: Remove unwanted packages
  ansible.builtin.package:
    name: "{{ remove_packages }}"
    state: absent
  ignore_errors: yes

