---
# tasks file for system-tuning
- name: Apply sysctl settings
  ansible.builtin.sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ sysctl_settings }}"

