---
# tasks file for network-configuration-set
# roles/network-configuration-automation/tasks/main.yml

- name: Configure network interface (Static/DHCP)
  ansible.builtin.template:
    src: network_config.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ network_interface }}"
  notify: Restart Network
  when: not use_dhcp

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  when: set_hostname

- name: Update /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "127.0.1.1 {{ hostname }}"
    state: present
  when: set_hostname

- name: Configure DNS servers
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
  when: dns_servers is defined

- name: Configure SSH settings
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify: Restart SSH
  when: disable_root_login

- name: Set SSH port
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?Port "
    line: "Port {{ ssh_port }}"
  notify: Restart SSH

- name: Enable and start firewall
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes
  when: firewall_enable

- name: Open required firewall ports
  ansible.builtin.firewalld:
    port: "{{ item }}/tcp"
    permanent: yes
    state: enabled
  with_items: "{{ open_ports }}"
  when: firewall_enable

- name: Enable and configure NTP
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: yes
  when: enable_ntp

- name: Configure NTP servers
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    line: "server {{ item }} iburst"
  with_items: "{{ ntp_servers }}"
  notify: Restart NTP
  when: enable_ntp
