# vars/main.yml
node_exporter_version: "1.5.0"
node_exporter_install_dir: "/usr/local/bin"
node_exporter_config_dir: "/etc/node_exporter"
node_exporter_user: "node_exporter"
node_exporter_group: "node_exporter"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
node_exporter_data_dir: "/var/lib/node_exporter"
node_exporter_service_name: "node_exporter"

