- name: Test connectivity to target servers
  hosts: all
  gather_facts: no
  roles:
    - connectivity-test

- name: Configure Network on Linux
  hosts: all
  become: yes
  roles:
    #- network-configuration-set
    #- user-management
    #- package-management
    #- system-tuning
    - monitoring
